# Generated by Django 3.2.16 on 2025-12-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
    ]
