# Generated by Django 3.2.16 on 2025-12-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_delete_tag_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
